version: '3'
services:
  neo4j:
      image: 310946103770.dkr.ecr.us-east-1.amazonaws.com/npss/neo4j:3.3.0
      environment:
        - NEO4J_AUTH=neo4j/test
        # These dont seem to be working though!
        - NEO4J_dbms.active_database=amundsen.db
        - NEO4J_dbms.directories.data=/neo4j/data
        - NEO4J_dbms.directories.logs=/var/log/neo4j
        - NEO4J_dbms.directories.import=/var/lib/neo4j/import
        - NEO4J_dbms.security.auth_enabled=false
        - NEO4J_dbms.connectors.default_listen_address=0.0.0.0
      volumes: 
        - amundsen-neo4j-data:/data
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      logging:
        driver: awslogs
        options: 
          awslogs-group: amundsen-neo4j
          awslogs-region: us-east-1
          awslogs-stream-prefix: amundsen-neo4j
  
  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: web
    volumes: 
        - amundsen-neo4j-data:/mnt/amundsen-neo4j-data
    ports: 
        - 8000:8000
    logging:
      driver: awslogs
      options: 
        awslogs-group: amundsencloudcmd
        awslogs-region: us-east-1
        awslogs-stream-prefix: amundsen-cloudcmd


volumes: 
  amundsen-neo4j-data:

